// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: comment.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommentClient is the client API for Comment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentClient interface {
	// Add comment
	CommentAdd(ctx context.Context, in *CommentAddRequest, opts ...grpc.CallOption) (*CommentAddResponse, error)
	// Get comment
	CommentGet(ctx context.Context, in *CommentGetRequest, opts ...grpc.CallOption) (*CommentGetResponse, error)
	// Get Comments list
	CommentList(ctx context.Context, in *CommentListRequest, opts ...grpc.CallOption) (*CommentListResponse, error)
	// Update Comment
	CommentUpdate(ctx context.Context, in *CommentUpdateRequest, opts ...grpc.CallOption) (*CommentUpdateResponse, error)
	// Delete Comment
	CommentDelete(ctx context.Context, in *CommentDeleteRequest, opts ...grpc.CallOption) (*CommentDeleteResponse, error)
}

type commentClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentClient(cc grpc.ClientConnInterface) CommentClient {
	return &commentClient{cc}
}

func (c *commentClient) CommentAdd(ctx context.Context, in *CommentAddRequest, opts ...grpc.CallOption) (*CommentAddResponse, error) {
	out := new(CommentAddResponse)
	err := c.cc.Invoke(ctx, "/ozon.dev.homework1.api.Comment/CommentAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) CommentGet(ctx context.Context, in *CommentGetRequest, opts ...grpc.CallOption) (*CommentGetResponse, error) {
	out := new(CommentGetResponse)
	err := c.cc.Invoke(ctx, "/ozon.dev.homework1.api.Comment/CommentGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) CommentList(ctx context.Context, in *CommentListRequest, opts ...grpc.CallOption) (*CommentListResponse, error) {
	out := new(CommentListResponse)
	err := c.cc.Invoke(ctx, "/ozon.dev.homework1.api.Comment/CommentList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) CommentUpdate(ctx context.Context, in *CommentUpdateRequest, opts ...grpc.CallOption) (*CommentUpdateResponse, error) {
	out := new(CommentUpdateResponse)
	err := c.cc.Invoke(ctx, "/ozon.dev.homework1.api.Comment/CommentUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentClient) CommentDelete(ctx context.Context, in *CommentDeleteRequest, opts ...grpc.CallOption) (*CommentDeleteResponse, error) {
	out := new(CommentDeleteResponse)
	err := c.cc.Invoke(ctx, "/ozon.dev.homework1.api.Comment/CommentDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentServer is the server API for Comment service.
// All implementations must embed UnimplementedCommentServer
// for forward compatibility
type CommentServer interface {
	// Add comment
	CommentAdd(context.Context, *CommentAddRequest) (*CommentAddResponse, error)
	// Get comment
	CommentGet(context.Context, *CommentGetRequest) (*CommentGetResponse, error)
	// Get Comments list
	CommentList(context.Context, *CommentListRequest) (*CommentListResponse, error)
	// Update Comment
	CommentUpdate(context.Context, *CommentUpdateRequest) (*CommentUpdateResponse, error)
	// Delete Comment
	CommentDelete(context.Context, *CommentDeleteRequest) (*CommentDeleteResponse, error)
	mustEmbedUnimplementedCommentServer()
}

// UnimplementedCommentServer must be embedded to have forward compatible implementations.
type UnimplementedCommentServer struct {
}

func (UnimplementedCommentServer) CommentAdd(context.Context, *CommentAddRequest) (*CommentAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentAdd not implemented")
}
func (UnimplementedCommentServer) CommentGet(context.Context, *CommentGetRequest) (*CommentGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentGet not implemented")
}
func (UnimplementedCommentServer) CommentList(context.Context, *CommentListRequest) (*CommentListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentList not implemented")
}
func (UnimplementedCommentServer) CommentUpdate(context.Context, *CommentUpdateRequest) (*CommentUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentUpdate not implemented")
}
func (UnimplementedCommentServer) CommentDelete(context.Context, *CommentDeleteRequest) (*CommentDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentDelete not implemented")
}
func (UnimplementedCommentServer) mustEmbedUnimplementedCommentServer() {}

// UnsafeCommentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentServer will
// result in compilation errors.
type UnsafeCommentServer interface {
	mustEmbedUnimplementedCommentServer()
}

func RegisterCommentServer(s grpc.ServiceRegistrar, srv CommentServer) {
	s.RegisterService(&Comment_ServiceDesc, srv)
}

func _Comment_CommentAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).CommentAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozon.dev.homework1.api.Comment/CommentAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).CommentAdd(ctx, req.(*CommentAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_CommentGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).CommentGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozon.dev.homework1.api.Comment/CommentGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).CommentGet(ctx, req.(*CommentGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_CommentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).CommentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozon.dev.homework1.api.Comment/CommentList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).CommentList(ctx, req.(*CommentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_CommentUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).CommentUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozon.dev.homework1.api.Comment/CommentUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).CommentUpdate(ctx, req.(*CommentUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comment_CommentDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServer).CommentDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ozon.dev.homework1.api.Comment/CommentDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServer).CommentDelete(ctx, req.(*CommentDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Comment_ServiceDesc is the grpc.ServiceDesc for Comment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Comment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ozon.dev.homework1.api.Comment",
	HandlerType: (*CommentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommentAdd",
			Handler:    _Comment_CommentAdd_Handler,
		},
		{
			MethodName: "CommentGet",
			Handler:    _Comment_CommentGet_Handler,
		},
		{
			MethodName: "CommentList",
			Handler:    _Comment_CommentList_Handler,
		},
		{
			MethodName: "CommentUpdate",
			Handler:    _Comment_CommentUpdate_Handler,
		},
		{
			MethodName: "CommentDelete",
			Handler:    _Comment_CommentDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comment.proto",
}
