-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS public.comments (
    id        integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment   text     NOT NULL,
    user_id   integer  NOT NULL,
    CONSTRAINT fk_users
        FOREIGN KEY(user_id)
        REFERENCES users(id)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS public.comments CASCADE;
-- +goose StatementEnd
