-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS public.users (
    id        integer      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      text         NOT NULL CONSTRAINT name_right CHECK(length(name) <= 10),
    password  text         NOT NULL CONSTRAINT password_right CHECK(length(password) between 6 and 10)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS public.users;
-- +goose StatementEnd
